FROM python:3.9-slim

# Installare librerie necessarie
RUN pip install requests

# Imposta la working directory all'interno del container
WORKDIR /app

# Copia i file del progetto nella working directory
COPY app/ /app/
COPY requirements.txt /app/

# Installa le dipendenze
RUN pip install --no-cache-dir -r requirements.txt

# Comando per eseguire lo script
CMD ["python", "setup_dashboard.py"]



